### ISSUE TITLE
Question about JoinSim algorithm

### ISSUE THREAD

**Issue by schatzopoulos** [mhnamaki/-L2P-for-Top-k-Graph-Query-Processing#1]
The algorithm implemented in the wsu.eecs.mlkd.KGQuery.algo.joinsim is one of the algorithms described in the following paper https://ieeexplore.ieee.org/document/6963491 ?

**Comment by mhnamaki** [comment]
wsu.eecs.mlkd.KGQuery.algo.joinsim is a legacy code I've got from a colleague and has not been used in our ICAPS paper, titled "learning to speed up query planning in graph databases".
I think "joinsim" is for "graph simulation" as an approximate pattern matching semantic.

**Comment by schatzopoulos** [comment]
Thank you very much for your response! Thank you for pointing to your paper, interesting work indeed.

**Comment by mhnamaki** [comment]
your welcome. good luck with your research though.
